### ISSUE TITLE
Where is this deployed + performance?

### ISSUE THREAD

**Issue by szym3n** [Ucnt/bro-json-to-tsv#1]
Is this script intended to be implemented on the RITA system or on the Security Onion sensor itself?

I am currently running a distributed SO environment so all the BRO (JSON) logs are being sent over to the management interface and there is currently no forwarding over to RITA because of the format issues (We can't switch to CSV as it messes up the rules and parsing on the SO console).

I currently have a temporary BRO sensor that captures in CSV format but I'd like to use the SO instead. Is this script to be ran on the SO sensor or the RITA system?

**Comment by Ucnt** [comment]
Great question.  I'll update the documentation to clarify.  To do it here as well:

High level:  The script does best to sit on the same box as RITA, run prior to RITA's import

My methodology:
- Bro logs are sent to an aggregation point 
    - I'm using GCS as the final location, via Stackdriver and google-fluentd
- On the box RITA is installed on: A cronjob downloads the new logs from GCS, runs the bro-json-to-tsv script to conver them, then imports those converted logs in a rolling import to RITA.

If you are able to, one of the below solutions may work:
1) Add a new log destination to each worker's /etc/syslog-ng/syslog.conf file.  
2) Have a separate system (e.g. google-fluentd) watch the /nsm/bro/logs/current/*.log files and send those logs to a central server.

**Comment by Ucnt** [comment]
To note, I pulled the logs off of the worker because that was easier for me.  Theoretically, you COULD pull the logs off of the manager as well but that occurs in the "so-logstash" docker container and I really didn't to start messing around with those internals.

**Comment by szym3n** [comment]
So it looks like I was able to connect the Worker (sensor) to my RITA/AIH system by creating the required users and all that.
For the following run command, is the input and output folder a folder for the 'current' directory of the copied bro logs? (Meaning, there is literally a directory called 'current' which contains data for the current day, however the folder created for the sensor contains historical data (For things from the days prior))

python3 run_parser.py --input_folder /json/folder/path --output_folder /output/folder/path

Input folder in my case: /opt/bro/remotelogs/sensor__1025447/
Output folder: /opt/bro/remotelogs/sensorTSV__1025447/

**Comment by Ucnt** [comment]
Hopefully this answers  the question...

Given JSON files:
/json/folder/path/first.log
/json/folder/path/second.log

Run: python3 run_parser.py --input_folder /json/folder/path --output_folder /output/folder/path

Resulting TSV:
/output/folder/path/first.log
/output/folder/path/second.log

So, every file in the /json/folder/path directory will  be read,  converted, and created  in /output/folder/path with the same name.

There is no current check to see if the file already exists in the output folder and  it  will be overwritten if it already exists.

So, for you everything in  /opt/bro/remotelogs/sensor__1025447/ will  be converted and put in /opt/bro/remotelogs/sensorTSV__1025447/

**Comment by szym3n** [comment]
That definitely clarifies it!
Thanks for the help.
I am currently experiencing a problem where the script will copy over the file structure but will not copy over any of the contents of those files. So all of the conn.*** or dns.*** files will be copied over to the new folder but they will be of size 0.

Also, does the script automatically embed itself inside a cronjob or does that have to be done manually? 

I apologize for the questions, but I'm very interested in what this script's purpose is!

**Comment by Ucnt** [comment]
Weird...I thought I put in enough try/except + print statements to give errors. Are the files in sub-folders?  e.g.  /opt/bro/remotelogs/sensor__1025447/2019-08-09

If you want to hit  me up to the side (since I saw you deleted the screenshot) I can work through it more directly.  My profile shows my webpage which has linkedin.

On the cronjob, I created a script and run something like this:
```
LOG_DIR_JSON=/tmp/logs/json
LOG_DIR_TSV=/tmp/logs/tsv
mkdir $LOG_DIR_JSON
mkdir $LOG_DIR_TSV

# GET THE LOGS INTO THE JSON FOLDER

# Convert logs
python3 /home/mattsvensson/bro-json-to-tsv/run_parser.py --input_folder $LOG_DIR_JSON --output_folder $LOG_DIR_TSV

##Import the logs, keeping 7 days of logs (7 days * 24 hours = 168 chunks)
/usr/local/bin/rita import --rolling --numchunks 168 $LOG_DIR_TSV week-dataset

# Remove the old json logs since you already imported them
rm $LOG_DIR_JSON/*
rm $LOG_DIR_TSV/*
```

Checking on my end right now with a few tests.

**Comment by Ucnt** [comment]
I just did a test on my logs and it works fine.  Any way you could copy in a modified version? e.g. an example of your logs?  The only way I can see that it would create a new file but nothing in it is if there were "#" at the start of all of the lines.  Otherwise, you should have some error message on the script (I think...)

**Comment by Ucnt** [comment]
I think I see what it is.  Give me a minute.

**Comment by Ucnt** [comment]
Can you do a git pull and try again.  I modified two files that might have been causing the issue.

Also, could you try:

* Cloning the repo
* removing files out of the tsv folder
* trying to run the scripts on the json folder
* seeing if you get output files in the tsv folder

I created that as a little bit of a test to be sure it was working on someone's machine as intended on a sample set.

**Comment by szym3n** [comment]
Hey, I can do some testing now, thanks for following up so quickly.
I'll try re-creating the script and see whether there is any difference.
To be clear there were folders inside the folder which was to get copied, but even those got copied over as 'files' with the size of 0 previously.

I'll see whether the change you made makes a difference.

**Comment by Ucnt** [comment]
The files should be in the root directory of the folder given.  I can work
today to modify the script to do subfolders as well.

e.g. if you give -i /tmp/logs/json     I don't think anything in
/tmp/logs/json/2019-09-10/ will be converted.  Just files in /tmp/logs/json

**Comment by szym3n** [comment]
Unfortunately, it seems like the files are still getting copied over with size of 0:
![image](https://user-images.githubusercontent.com/37544898/64633621-900a6b80-d3c9-11e9-9bc7-e404660567c4.png)

This is the error I seem to be getting on all of the files:

Error parsing /opt/bro/remotelogs/CABRPSEIDS04__1025447/2019-09-10/http_ens192.03:00:00-04:00:00.log - [Not a directory: '/opt/bro/remotelogs/CABRPSEIDS04tsv/2019-09-10/http_ens192.03:00:00-04:00:00.log'

Seems like the directory is being made like a 'file' instead of an actual directory.

**Comment by Ucnt** [comment]
Yep.  It's the recursive nature of the directories. Working it now.

**Comment by Ucnt** [comment]
Just added subdirectory handling.  Examples included.

Can you try again?

Being sure all files in json/ are gunzipped
Done gunzipping files in json/
Converting files from JSON to TSV
  0%|
                                                    | 0/9 [00:00<?,
?it/s]Running: json/conn.log
Running: json/ssl.log
Running: json/http.log
Running: json/dns.log
Making directory: tsv/subdir
Running: json/subdir/http-subdir.log
Running: json/subdir/ssl-subdir.log
Running: json/subdir/conn-subdir.log
Running: json/subdir/dns-subdir.log
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏
           | 8/9 [00:00<00:00, 77.87it/s]

**Comment by szym3n** [comment]
The .log files appear to be copying properly now, however the Folders are still getting created as 'files':
![image](https://user-images.githubusercontent.com/37544898/64640755-a53ac680-d3d8-11e9-9843-1250b73b9687.png)
Could this error have something to do with it?
Error parsing /opt/bro/remotelogs/CABRPSEIDS04__1025447/2019-09-07 - [Errno 21] Is a directory: '/opt/bro/remotelogs/CABRPSEIDS04__1025447**//**2019-09-07'
As you can see, there are two backslashes before the '2019-09-07' directory.

There are also many parsing errors
Error parsing /opt/bro/remotelogs/CABRPSEIDS04__1025447/2019-09-10/x509.00:00:00-01:00:00.log - ''
Error parsing /opt/bro/remotelogs/CABRPSEIDS04__1025447/2019-09-10/x509.12:00:00-13:00:00.log.gz - 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Can you recommend how I can troubleshoot these?

**Comment by Ucnt** [comment]
Can you try running it on the example json/ and tsv/ folders? I want to be
sure that at least that works right on your system.

I'll look into the other parts.

I did put in a replace of "//" with "/" so it shouldn't be doing that
anymore...I'll make it a while loop to be sure...

**Comment by Ucnt** [comment]
Just did another push with the while loop on "//" to "/" conversion and
handling gzipped files in all subdirectories.

Few thoughts on the screenshot and logs

1) the gz woudln't work anyway.  The above handling of the files should
have fixed that as it's now doing gunzip file by file.

2) The conn-summary items probably aren't in the right format so those wouldn't get converted anyway.  A new file would be created, empty, but nothing in it since it doesn't match a template.

3) Try deleting everything from the tsv output folder then trying again.  if you have a file with the name "2019-09-07" linux won't create a directory with that same name.

See below for my successful execution with the test folder.

mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$
./run_parser.py -i json/ -o tsv/
Converting files from JSON to TSV
  0%|
                                                    | 0/9 [00:00<?,
?it/s]Running: json/conn.log
Running: json/ssl.log
Running: json/http.log
Running: json/dns.log
*Making directory: tsv/subdir*
*Uncompressing json/subdir/ssl-subdir.log.gz*
Running: json/subdir/ssl-subdir.log

Running: json/subdir/http-subdir.log
Running: json/subdir/conn-subdir.log
Running: json/subdir/dns-subdir.log
 89%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏
           | 8/9 [00:00<00:00, 75.05it/s]
mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$ ls
__init__.py  json  module  README.md  requirements.txt  run_parser.py  tsv
mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$ ls tsv/
conn.log  dns.log  http.log  ssl.log  subdir
mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$ ls
tsv/subdir/
conn-subdir.log  dns-subdir.log  http-subdir.log  ssl-subdir.log
mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$ ls -la
tsv/
total 56
drwxrwxr-x 3 mattsvensson mattsvensson 4096 Sep 10 14:51 .
drwxrwxr-x 6 mattsvensson mattsvensson 4096 Sep 10 14:51 ..
-rw-rw-r-- 1 mattsvensson mattsvensson  509 Sep 10 14:51 conn.log
-rw-rw-r-- 1 mattsvensson mattsvensson  442 Sep 10 14:51 dns.log
-rw-rw-r-- 1 mattsvensson mattsvensson  660 Sep 10 14:51 http.log
-rw-rw-r-- 1 mattsvensson mattsvensson  520 Sep 10 14:51 ssl.log
drwxrwxr-x 2 mattsvensson mattsvensson 4096 Sep 10 14:51 subdir
mattsvensson@Ubuntu-Desktop:~/Dropbox/it/git/repos/bro-json-to-tsv$ ls -a
tsv/subdir/
.  ..  conn-subdir.log  dns-subdir.log  http-subdir.log  ssl-subdir.log

**Comment by Ucnt** [comment]
To be sure the main item is covered, try deleting the output folder items.  

The folder 2019-09-07 won't be created if there is a file with that same name.

**Comment by szym3n** [comment]
1. The Conversion script works as intended between the 'json' and the 'tsv' folder included in the ZIP
2. I've been running the script with the output folder completely empty every time. (Clearing it after every attempt)

Currently Attempting to run your new version on the entire directory to see if there are any differences.

**Comment by Ucnt** [comment]
Thought I'd check in and see if the new version worked or still had
unexpected behavior.

**Comment by szym3n** [comment]
Yes Actually, thanks for the follow up!
I didn't let you know prior as I was waiting to test it out before hand, but it seems like everything went as planned and it's working.
I will let you know if there are any issues I come across.
Thanks for the help!

**Comment by Ucnt** [comment]
Just made a change.  Please be sure you got the recent update. 

I made a noob elseif vs if statement mixup in one of the files.  Not sure if it impacted you or not.

**Comment by smissu** [comment]
Is the script supposed to overwrite/remove the .gz files in the ingest directory? When I run the script, all of the files are converted to .log in the ingest directory. The files are also in the output directory as well.

**Comment by Ucnt** [comment]
Gunzip does remove the gz file when it decompresses. I could add an option
to keep it if you want.  Gunzip has a --keep option.

**Comment by smissu** [comment]
Yes, I would like the original directory to remain unchanged with the
decompressed tsv logs in the output (-o) directory.

**Comment by Ucnt** [comment]
I just added the -k/--keep_original to keep the .gz file.

It leaves the uncompressed file right now as well.  I presume you'd like the uncompressed file to be removed at the end?

e.g. there's a conn.log.gz.  That gets uncompressed so now there's conn.log AND conn.log.gz.  Once the conversion is done, the conn.log file should be removed from the original location, leaving the original directory unchanged, as you noted.

**Comment by Ucnt** [comment]
Assuming so just included the deletion of the uncompressed file so the original directory will remain the same.

**Comment by Ucnt** [comment]
FYI, RITA now support JSON natively.
